### ISSUE TITLE
var array inside struct can't be assigned to

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#107]
```
struct foo {
   var int[2] a;
}

kn main() int {
   struct foo my_foo = foo { .a=[2,3] };
   my_foo.a = 5; /* this should be allowed */
   0
}
```

fails compilation with error

```
Uncaught exception: Parsing.Parse_error Raised at file "parsing.ml", line 136, characters 14-25 Called from file "parsing.ml", line 162, characters 4-28 Re-raised at file "parsing.ml", line 181, characters 14-17 Called from file "shuxc.ml", line 27, characters 11-46
```

**Comment by Contentmaudlin** [comment]
There are things that are wrong with this code.

First of all, cannot indicate whether individual fields of a struct will be `var` or not. Whether they are mutable or not depends entirely on the mutability of the array that is declared. 

``` 
struct foo {
   int[2] a;
}

kn main() int {
   struct foo my_foo = foo { .a=[2,3] };
   my_foo.a = 5; /* this should be allowed */
   0
}
```

Second, you are setting `my_foo.a = 5;`, which is setting an array equal to an integer. This should be an array instead `my_foo a = [1,2]`;

This will also not work because Now `struct foo` is declared without the `var` prefix, meaning it's elements are not mutable. The final working iteration will be as follows:

```
struct foo {
   int[2] a;
}

kn main() int {
   var struct foo my_foo = foo { .a=[2,3] };
   my_foo.a = [1,2]; /* this should be allowed */
   0
}
```

**Comment by Contentmaudlin** [comment]
Note to self, currently able to do assigns to struct that are not declared with `var`. Need to forbid this.

**Comment by lucas-schuermann** [comment]
lol damn my 4am code really sucks. ill update this test
